# Generated by Django 4.2.3 on 2023-07-28 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password'),
        ),
    ]
