# Generated by Django 4.2.3 on 2023-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='from_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='to_year',
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
